2025-03-10 10:32:53,080 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:32:53,082 INFO    Thread-13 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103253-8u8n3dby\logs\debug.log
2025-03-10 10:32:53,105 INFO    Thread-13 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103253-8u8n3dby\logs\debug-internal.log
2025-03-10 10:32:53,106 INFO    Thread-13 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:32:53,106 INFO    Thread-13 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:32:53,107 INFO    Thread-13 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:32:53,107 ERROR   Thread-13 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:32:53,227 INFO    Thread-13 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103257-rxj6tjxk\logs\debug.log
2025-03-10 10:32:57,267 INFO    Thread-16 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103257-rxj6tjxk\logs\debug-internal.log
2025-03-10 10:32:57,268 INFO    Thread-16 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:32:57,268 INFO    Thread-16 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'rmsprop', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:32:57,268 INFO    Thread-16 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:32:57,268 ERROR   Thread-16 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:32:57,277 INFO    Thread-16 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:02,826 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:33:02,828 INFO    Thread-19 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103302-rcpfcqz9\logs\debug.log
2025-03-10 10:33:02,828 INFO    Thread-19 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103302-rcpfcqz9\logs\debug-internal.log
2025-03-10 10:33:02,828 INFO    Thread-19 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:33:02,830 INFO    Thread-19 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 10:33:02,830 INFO    Thread-19 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:33:02,830 ERROR   Thread-19 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:33:02,843 INFO    Thread-19 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:08,155 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:33:08,155 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-10 10:33:38,135 INFO    MainThread:16088 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-10 10:33:38,188 INFO    MainThread:16088 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=100
2025-03-10 10:33:39,153 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:33:39,154 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:33:39,154 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:33:39,154 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:33:39,155 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:33:39,155 INFO    Thread-23 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103339-qpsaq9x2\logs\debug.log
2025-03-10 10:33:39,156 INFO    Thread-23 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103339-qpsaq9x2\logs\debug-internal.log
2025-03-10 10:33:39,157 INFO    Thread-23 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:33:39,158 INFO    Thread-23 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:33:39,158 INFO    Thread-23 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:33:39,159 ERROR   Thread-23 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:33:39,174 INFO    Thread-23 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:44,605 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:33:44,606 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103344-yxxst9ki\logs\debug.log
2025-03-10 10:33:44,631 INFO    Thread-26 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103344-yxxst9ki\logs\debug-internal.log
2025-03-10 10:33:44,632 INFO    Thread-26 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:33:44,632 INFO    Thread-26 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:33:44,634 INFO    Thread-26 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:33:44,635 ERROR   Thread-26 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:33:44,644 INFO    Thread-26 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:50,153 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:33:50,153 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-10 10:34:00,524 INFO    MainThread:16088 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-10 10:34:00,583 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:34:00,583 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
