2025-03-10 10:30:42,808 INFO    MainThread:16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:30:42,809 INFO    MainThread:16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:30:42,809 INFO    MainThread:16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:30:42,809 INFO    MainThread:16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:30:42,809 INFO    MainThread:16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:30:42,810 INFO    MainThread:16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103042-xot07ain\logs\debug.log
2025-03-10 10:30:42,811 INFO    MainThread:16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103042-xot07ain\logs\debug-internal.log
2025-03-10 10:30:42,811 INFO    MainThread:16088 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000260F573D340>
2025-03-10 10:30:42,812 INFO    MainThread:16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:30:42,812 INFO    MainThread:16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-10 10:30:42,813 INFO    MainThread:16088 [wandb_init.py:init():784] starting backend
2025-03-10 10:30:42,813 INFO    MainThread:16088 [wandb_init.py:init():788] sending inform_init request
2025-03-10 10:30:42,880 INFO    MainThread:16088 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-03-10 10:30:42,881 INFO    MainThread:16088 [wandb_init.py:init():803] backend started and connected
2025-03-10 10:30:42,891 INFO    MainThread:16088 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-10 10:30:42,912 INFO    MainThread:16088 [wandb_run.py:_label_probe_notebook():1214] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 42675: character maps to <undefined>
2025-03-10 10:30:42,912 INFO    MainThread:16088 [wandb_init.py:init():896] updated telemetry
2025-03-10 10:30:43,002 INFO    MainThread:16088 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-10 10:30:43,414 INFO    MainThread:16088 [wandb_init.py:init():995] starting run threads in backend
2025-03-10 10:30:44,118 INFO    MainThread:16088 [wandb_run.py:_console_start():2377] atexit reg
2025-03-10 10:30:44,118 INFO    MainThread:16088 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-10 10:30:44,118 INFO    MainThread:16088 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-10 10:30:44,118 INFO    MainThread:16088 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-10 10:30:44,128 INFO    MainThread:16088 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-10 10:30:44,133 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:30:44,133 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-10 10:31:03,848 INFO    MainThread:16088 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-10 10:31:28,420 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:31:28,421 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-10 10:32:45,610 INFO    MainThread:16088 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-10 10:32:45,619 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:32:45,619 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-10 10:32:50,791 INFO    MainThread:16088 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-10 10:32:50,797 INFO    MainThread:16088 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=100
2025-03-10 10:32:51,641 WARNING MsgRouterThr:16088 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-10 10:32:51,698 INFO    MsgRouterThr:16088 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-10 10:32:53,080 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:32:53,081 INFO    Thread-13 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:32:53,082 INFO    Thread-13 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103253-8u8n3dby\logs\debug.log
2025-03-10 10:32:53,105 INFO    Thread-13 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103253-8u8n3dby\logs\debug-internal.log
2025-03-10 10:32:53,106 INFO    Thread-13 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:32:53,106 INFO    Thread-13 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'sgd', 'weight_decay': 0.0005, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:32:53,107 INFO    Thread-13 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:32:53,107 ERROR   Thread-13 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:32:53,227 INFO    Thread-13 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:32:57,266 INFO    Thread-16 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103257-rxj6tjxk\logs\debug.log
2025-03-10 10:32:57,267 INFO    Thread-16 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103257-rxj6tjxk\logs\debug-internal.log
2025-03-10 10:32:57,268 INFO    Thread-16 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:32:57,268 INFO    Thread-16 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 64, 'epochs': 10, 'hidden_layers': 3, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'rmsprop', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:32:57,268 INFO    Thread-16 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:32:57,268 ERROR   Thread-16 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:32:57,277 INFO    Thread-16 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:02,826 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:33:02,827 INFO    Thread-19 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:33:02,828 INFO    Thread-19 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103302-rcpfcqz9\logs\debug.log
2025-03-10 10:33:02,828 INFO    Thread-19 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103302-rcpfcqz9\logs\debug-internal.log
2025-03-10 10:33:02,828 INFO    Thread-19 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:33:02,830 INFO    Thread-19 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 32, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 64, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-10 10:33:02,830 INFO    Thread-19 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:33:02,830 ERROR   Thread-19 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:33:02,843 INFO    Thread-19 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:08,155 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:33:08,155 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-10 10:33:38,135 INFO    MainThread:16088 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-10 10:33:38,188 INFO    MainThread:16088 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=100
2025-03-10 10:33:39,153 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:33:39,154 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:33:39,154 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:33:39,154 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:33:39,155 INFO    Thread-23 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:33:39,155 INFO    Thread-23 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103339-qpsaq9x2\logs\debug.log
2025-03-10 10:33:39,156 INFO    Thread-23 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103339-qpsaq9x2\logs\debug-internal.log
2025-03-10 10:33:39,157 INFO    Thread-23 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:33:39,158 INFO    Thread-23 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 64, 'epochs': 10, 'hidden_layers': 4, 'hidden_size': 128, 'learning_rate': 0.001, 'optimizer': 'rmsprop', 'weight_decay': 0, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:33:39,158 INFO    Thread-23 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:33:39,159 ERROR   Thread-23 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:33:39,174 INFO    Thread-23 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:44,605 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-10 10:33:44,606 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Configure stats pid to 16088
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Preethi\.config\wandb\settings
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from c:\Users\Preethi\Downloads\Assgn1_DL\wandb\settings
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-10 10:33:44,607 INFO    Thread-26 (_run_job):16088 [wandb_init.py:setup_run_log_directory():647] Logging user logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103344-yxxst9ki\logs\debug.log
2025-03-10 10:33:44,631 INFO    Thread-26 (_run_job):16088 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to c:\Users\Preethi\Downloads\Assgn1_DL\wandb\run-20250310_103344-yxxst9ki\logs\debug-internal.log
2025-03-10 10:33:44,632 INFO    Thread-26 (_run_job):16088 [wandb_init.py:init():761] calling init triggers
2025-03-10 10:33:44,632 INFO    Thread-26 (_run_job):16088 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 16, 'epochs': 5, 'hidden_layers': 4, 'hidden_size': 32, 'learning_rate': 0.001, 'optimizer': 'nesterov', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-10 10:33:44,634 INFO    Thread-26 (_run_job):16088 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-10 10:33:44,635 ERROR   Thread-26 (_run_job):16088 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 779, in init
    with telemetry.context() as tel:
         ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\Preethi\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2025-03-10 10:33:44,644 INFO    Thread-26 (_run_job):16088 [wandb_run.py:_finish():2112] finishing run mm21b051-iitmaana/DeepLearning1/xot07ain
2025-03-10 10:33:50,153 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:33:50,153 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-10 10:34:00,524 INFO    MainThread:16088 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-10 10:34:00,583 INFO    MainThread:16088 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-10 10:34:00,583 INFO    MainThread:16088 [wandb_init.py:_pause_backend():564] pausing backend
